name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest

      - name: Run flake8
        run: flake8

      - name: Save CI artifacts
        run: |
          mkdir -p ci-artifacts
          cp -r ./* ci-artifacts/
        if: always()
